### ISSUE TITLE
How to add the next minor branch

### ISSUE THREAD

**Issue by robbinjanssen** [mkurz/release-drafter-test#7]
Hi,

Got a followup question on this release flow, we have two branches configured based on https://github.com/release-drafter/release-drafter/issues/656#issuecomment-806184887

The only difference is that my `release-drafter-master.yml` has an `exclude-labels` config containing `skip-changelog` and `hotfix`.

Let's start from the beginning: 

Once there was a `master` branch, we add a bunch of commits and we tag `v1.0.0`.
- Question 1. Do I branch v1.0.x based on `master`, or on the `v1.0.0` tag?

Now we have a `v1.0.x` branch, and we continue developing on our `master` branch.
1. Cool, we add a new feature to the `master` branch, the release notes are updated and we see the `v1.1.0` drafter
2. Oh no! Something broken and we require a hotfix. We make a pull request from `hot-fix-patch` to `v1.0.x` and merge it. We add a label "hotfix". The release notes get updated and `v1.0.1` is drafted. We tag `v1.0.1` to make sure our production code is still working.

Of course we don't want our master branch to be broken, so we create a pull request to merge `v1.0.x` into `master`. This PR also gets the label "skip-changelog".

Master is up to date and now we add some more features. Time for our next release!
We publish our draft and tag version `v1.1.0` based on the master branch.

- Question 2 can we now remove `v1.0.x`?
- Question 3 again, do I create `v1.1.x` based off on `master` or the `v1.1.0` tag?

We then update the `release-drafter-v1.0.x.yml` to `v1.1.x.yml` and also the `draft-release` workflow, however... I'm facing some issues where the draft generated by the `v1.1.x` branch  contains all changes already released in the `v1.1.0`? Is there any way to prevent this?

If this is all unclear I can try and setup a demo repo containing the problem

**Comment by mkurz** [comment]
Sorry, I didn't have time, did you solve your problem?

**Comment by robbinjanssen** [comment]
in a way yes, by tagging a pre-release of v1.1.0. Kind of a workaround though but if it works, it works :-)
